package com.lanou.mirror.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CACHE".
 */
public class Cache {

    private Long id;
    private String city;
    private String price;
    private String url;
    private String description;
    private String brand;

    public Cache() {
    }

    public Cache(Long id) {
        this.id = id;
    }

    public Cache(Long id, String city, String price, String url, String description, String brand) {
        this.id = id;
        this.city = city;
        this.price = price;
        this.url = url;
        this.description = description;
        this.brand = brand;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getUrl() {
        return url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getBrand() {
        return brand;
    }

    public void setBrand(String brand) {
        this.brand = brand;
    }

}
